# Generated by Django 4.2.27 on 2026-04-26 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='amount_paid',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='emi_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipregistration',
            name='razorpay_order_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='base_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='gst_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipregistration',
            name='payment_type',
            field=models.CharField(max_length=20),
        ),
    ]
